version: "3"
services:
  db:
    image: postgres:13-alpine
    restart: always
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - PGUSER:postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kefir_db
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    expose:
      - 5432
  web:
    container_name: app
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - .:/task_kefir
    ports:
      - 8000:8000
    restart: always
    env_file:
      - ./.env
    depends_on:
      - db
    expose:
      - 8000
volumes:
  postgres_data: